# Generated by Django 3.0.3 on 2020-08-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0068_auto_20200820_1809'),
        ('users', '0002_auto_20200823_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelevisionRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Television - Rating',
                'verbose_name_plural': 'Television - Ratings',
            },
        ),
    ]
