# Generated by Django 3.0.3 on 2020-08-24 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0068_auto_20200820_1809'),
        ('users', '0003_televisionrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmrating',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AddField(
            model_name='televisionrating',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='televisionrating',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Television'),
        ),
    ]
