# Generated by Django 3.0.3 on 2020-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200824_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='filmrating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='televisionrating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='videogamerating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='webseriesrating',
            name='review',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
