# Generated by Django 3.0.3 on 2020-09-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0082_auto_20200901_1510'),
        ('users', '0007_auto_20200824_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.TextField(default='Profile Section', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSectionWebSeriesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInSection', models.IntegerField(default=1)),
                ('profileSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileSection')),
                ('webSeries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSectionVideoGameMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInSection', models.IntegerField(default=1)),
                ('profileSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileSection')),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSectionTelevisionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInSection', models.IntegerField(default=1)),
                ('profileSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileSection')),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSectionFilmMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInSection', models.IntegerField(default=1)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film')),
                ('profileSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileSection')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSectionBookMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInSection', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book')),
                ('profileSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ProfileSection')),
            ],
        ),
    ]
