# Generated by Django 3.0.3 on 2020-09-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profilesection_profilesectionbookmapping_profilesectionfilmmapping_profilesectiontelevisionmapping_p'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilesectionbookmapping',
            options={'verbose_name': 'Profile Section - Book Mapping', 'verbose_name_plural': 'Profile Sections - Book Mappings'},
        ),
        migrations.AlterModelOptions(
            name='profilesectionfilmmapping',
            options={'verbose_name': 'Profile Section - Film Mapping', 'verbose_name_plural': 'Profile Sections - Films Mappings'},
        ),
        migrations.AlterModelOptions(
            name='profilesectiontelevisionmapping',
            options={'verbose_name': 'Profile Section - Television Mapping', 'verbose_name_plural': 'Profile Sections - Television Mappings'},
        ),
        migrations.AlterModelOptions(
            name='profilesectionvideogamemapping',
            options={'verbose_name': 'Profile Section - Video Game Mapping', 'verbose_name_plural': 'Profile Sections - Video Games Mappings'},
        ),
        migrations.AlterModelOptions(
            name='profilesectionwebseriesmapping',
            options={'verbose_name': 'Profile Section - Web Series Mapping', 'verbose_name_plural': 'Profile Sections - Web Series Mappings'},
        ),
    ]
