# Generated by Django 3.0.3 on 2020-09-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200908_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmrating',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
