# Generated by Django 3.0.3 on 2020-09-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200908_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='televisionrating',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='videogamerating',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='webseriesrating',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
