# Generated by Django 3.0.3 on 2021-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210128_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesection',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
