# Generated by Django 3.0.3 on 2021-03-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profilesection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesection',
            name='type',
            field=models.TextField(default='Films', max_length=10),
        ),
    ]
