# Generated by Django 3.0.3 on 2021-03-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_auto_20210313_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesection',
            name='type',
            field=models.CharField(default='Films', max_length=11),
        ),
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userA', to=settings.AUTH_USER_MODEL)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userB', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
