# Generated by Django 3.0.3 on 2021-03-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210314_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'User Follows', 'verbose_name_plural': 'User Follows'},
        ),
    ]
