# Generated by Django 3.0.3 on 2021-03-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210315_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesection',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
