# Generated by Django 3.0.3 on 2021-04-02 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0136_auto_20210330_1143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_profilesection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filmrating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='televisionrating',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisionrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistbookmapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='userlistbookmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistfilmmapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='userlistfilmmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlisttelevisionmapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='userlisttelevisionmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistvideogamemapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistvideogamemapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='userlistwebseriesmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlistwebseriesmapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='videogamerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videogamerating',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='webseriesrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webseriesrating',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.CreateModel(
            name='FilmRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
