# Generated by Django 3.0.3 on 2025-01-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_userusersimilarities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='userA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollows',
            name='userB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userB', to=settings.AUTH_USER_MODEL),
        ),
    ]
