# Generated by Django 3.0.3 on 2020-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='boxOffice',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='film',
            name='length',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.CharField(default='NoSynopsisSpecified', max_length=500),
        ),
        migrations.AddField(
            model_name='television',
            name='epsiodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='television',
            name='synopsis',
            field=models.CharField(default='NoSynopsisSpecified', max_length=500),
        ),
    ]
