# Generated by Django 3.0.3 on 2020-04-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200414_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imageFilePath',
            field=models.CharField(default='NoImagePathSpecified', max_length=500),
        ),
    ]
