# Generated by Django 3.0.3 on 2020-04-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_television_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videogamepersonmapping',
            old_name='television',
            new_name='videogame',
        ),
    ]
