# Generated by Django 3.0.3 on 2020-04-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_franchise_posterfilepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageFilePath',
        ),
        migrations.AddField(
            model_name='book',
            name='posterFilePath',
            field=models.CharField(default='https://i.gyazo.com/94770d8db3ef2cf193553e34f6e29e2d.png', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.CharField(default='NoSynopsisSpecified', max_length=500),
        ),
        migrations.AddField(
            model_name='videogame',
            name='synopsis',
            field=models.CharField(default='NoSynopsisSpecified', max_length=500),
        ),
        migrations.AddField(
            model_name='webseries',
            name='synopsis',
            field=models.CharField(default='NoSynopsisSpecified', max_length=500),
        ),
        migrations.AlterField(
            model_name='television',
            name='posterFilePath',
            field=models.CharField(default='https://i.gyazo.com/94770d8db3ef2cf193553e34f6e29e2d.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='posterFilePath',
            field=models.CharField(default='https://i.gyazo.com/94770d8db3ef2cf193553e34f6e29e2d.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='posterFilePath',
            field=models.CharField(default='https://i.gyazo.com/94770d8db3ef2cf193553e34f6e29e2d.png', max_length=500),
        ),
    ]
