# Generated by Django 3.0.3 on 2020-04-18 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20200417_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameFranchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoFranchiseNameSpecified', max_length=500)),
                ('posterFilePath', models.CharField(default='https://i.gyazo.com/94770d8db3ef2cf193553e34f6e29e2d.png', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='videogamefranchisemapping',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchise'),
        ),
    ]
