# Generated by Django 3.0.3 on 2020-04-18 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20200418_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoConsoleNameSpecified', max_length=500)),
                ('shortName', models.CharField(default='NoShortConsoleNameSpecified', max_length=500)),
                ('release', models.DateField(default=django.utils.timezone.now)),
                ('imageFilePath', models.CharField(default='https://i.gyazo.com/94770d8db3ef2cf193553e34f6e29e2d.png', max_length=500)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGameConsoleMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Console')),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
            ],
        ),
    ]
