# Generated by Django 3.0.3 on 2020-04-18 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_console_videogameconsolemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='television',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
