# Generated by Django 3.0.3 on 2020-04-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_auto_20200418_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='posterFilePath',
            new_name='imageFilePath',
        ),
    ]
