# Generated by Django 3.0.3 on 2020-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_auto_20200418_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpersonmapping',
            name='character',
            field=models.CharField(default='Not a Character or Unknown', max_length=500),
        ),
    ]
