# Generated by Django 3.0.3 on 2020-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_filmpersonmapping_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionpersonmapping',
            name='character',
            field=models.CharField(default='Not a Character or Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='videogamepersonmapping',
            name='character',
            field=models.CharField(default='Not a Character or Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='webseriespersonmapping',
            name='character',
            field=models.CharField(default='Not a Character or Unknown', max_length=500),
        ),
    ]
