# Generated by Django 3.0.3 on 2020-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_auto_20200703_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpersonmapping',
            name='character',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='televisionpersonmapping',
            name='character',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='videogamepersonmapping',
            name='character',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='webseriespersonmapping',
            name='character',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
