# Generated by Django 3.0.3 on 2020-07-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_auto_20200703_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmpersonmapping',
            name='character',
        ),
        migrations.RemoveField(
            model_name='televisionpersonmapping',
            name='character',
        ),
        migrations.RemoveField(
            model_name='videogamepersonmapping',
            name='character',
        ),
        migrations.RemoveField(
            model_name='webseriespersonmapping',
            name='character',
        ),
    ]
