# Generated by Django 3.0.3 on 2020-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20200703_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpersonmapping',
            name='character',
            field=models.CharField(default='', max_length=500),
        ),
    ]
