# Generated by Django 3.0.3 on 2020-07-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_filmpersonmapping_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSeriesFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
                ('webSeries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.WebSeries')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGameFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchise')),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGameFranchiseSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoVideoGameFranchiseSubCategoryNameSpecified', max_length=500)),
                ('parentFranchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchise')),
            ],
        ),
        migrations.CreateModel(
            name='TelevisionFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Television')),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoFranchiseSubCategoryNameSpecified', max_length=500)),
                ('parentFranchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='FilmFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Film')),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='BookFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Book')),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
            ],
        ),
    ]
