# Generated by Django 3.0.3 on 2020-07-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0019_bookfranchisesubcategorymapping_filmfranchisesubcategorymapping_franchisesubcategory_televisionfranc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamefranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchiseSubcategory'),
        ),
    ]
