# Generated by Django 3.0.3 on 2020-07-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_auto_20200703_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='filmfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='televisionfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='webseriesfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.FranchiseSubcategory'),
        ),
    ]
