# Generated by Django 3.0.3 on 2020-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_auto_20200703_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmpersonmapping',
            name='billing',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='televisionpersonmapping',
            name='billing',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='televisionpersonmapping',
            name='character',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webseriespersonmapping',
            name='billing',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='webseriespersonmapping',
            name='character',
            field=models.CharField(default='', max_length=500),
        ),
    ]
