# Generated by Django 3.0.3 on 2020-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_auto_20200704_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmpersonmapping',
            name='character',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='televisionpersonmapping',
            name='character',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='webseriespersonmapping',
            name='character',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
