# Generated by Django 3.0.3 on 2020-07-06 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_auto_20200705_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webseries',
            name='episodes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='webseries',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webseries',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
    ]
