# Generated by Django 3.0.3 on 2020-07-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_auto_20200706_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Books', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookcompanymapping',
            options={'verbose_name': 'Book - Company Mapping', 'verbose_name_plural': 'Books - Company Mappings'},
        ),
        migrations.AlterModelOptions(
            name='bookfranchisemapping',
            options={'verbose_name': 'Books - Franchise Mapping', 'verbose_name_plural': 'Books - Franchise Mappings'},
        ),
        migrations.AlterModelOptions(
            name='bookfranchisesubcategorymapping',
            options={'verbose_name': 'Books - Franchise  Subcategory Mapping', 'verbose_name_plural': 'Books - Franchise  Subcategory Mappings'},
        ),
        migrations.AlterModelOptions(
            name='bookgenremapping',
            options={'verbose_name': 'Books - Genre Mapping', 'verbose_name_plural': 'Books - Genre Mappings'},
        ),
        migrations.AlterModelOptions(
            name='bookpersonmapping',
            options={'verbose_name': 'Book - Person Mapping', 'verbose_name_plural': 'Books - Person Mappings'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companyrole',
            options={'verbose_name': 'Company - Role Type', 'verbose_name_plural': 'Companies - Role Types'},
        ),
        migrations.AlterModelOptions(
            name='console',
            options={'verbose_name': 'Video Game Console', 'verbose_name_plural': 'Video Game Consoles'},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterModelOptions(
            name='filmcompanymapping',
            options={'verbose_name': 'Films - Company Mapping', 'verbose_name_plural': 'Films - Company Mappings'},
        ),
        migrations.AlterModelOptions(
            name='filmfranchisemapping',
            options={'verbose_name': 'Films - Franchise Mapping', 'verbose_name_plural': 'Films - Franchise Mappings'},
        ),
        migrations.AlterModelOptions(
            name='filmfranchisesubcategorymapping',
            options={'verbose_name': 'Films - Franchise  Subcategory Mapping', 'verbose_name_plural': 'Films - Franchise  Subcategory Mappings'},
        ),
        migrations.AlterModelOptions(
            name='filmgenremapping',
            options={'verbose_name': 'Films - Genre Mapping', 'verbose_name_plural': 'Films - Genre Mappings'},
        ),
        migrations.AlterModelOptions(
            name='filmpersonmapping',
            options={'verbose_name': 'Films - Person Mapping', 'verbose_name_plural': 'Films - Person Mappings'},
        ),
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name': 'Franchise', 'verbose_name_plural': 'Franchises'},
        ),
        migrations.AlterModelOptions(
            name='franchisesubcategory',
            options={'verbose_name': 'Franchise - Subcategory', 'verbose_name_plural': 'Franchises - Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre - Standard', 'verbose_name_plural': 'Genres - Standard'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personrole',
            options={'verbose_name': 'Person - Role Type', 'verbose_name_plural': 'People - Role Types'},
        ),
        migrations.AlterModelOptions(
            name='television',
            options={'verbose_name': 'Television', 'verbose_name_plural': 'Television'},
        ),
        migrations.AlterModelOptions(
            name='televisioncompanymapping',
            options={'verbose_name': 'Television - Company Mapping', 'verbose_name_plural': 'Television - Company Mappings'},
        ),
        migrations.AlterModelOptions(
            name='televisionfranchisemapping',
            options={'verbose_name': 'Television - Franchise Mapping', 'verbose_name_plural': 'Television - Franchise Mappings'},
        ),
        migrations.AlterModelOptions(
            name='televisionfranchisesubcategorymapping',
            options={'verbose_name': 'Television - Franchise  Subcategory Mapping', 'verbose_name_plural': 'Television - Franchise  Subcategory Mappings'},
        ),
        migrations.AlterModelOptions(
            name='televisiongenremapping',
            options={'verbose_name': 'Television - Genre Mapping', 'verbose_name_plural': 'Television - Genre Mappings'},
        ),
        migrations.AlterModelOptions(
            name='televisionpersonmapping',
            options={'verbose_name': 'Television - Person Mapping', 'verbose_name_plural': 'Television - Person Mappings'},
        ),
        migrations.AlterModelOptions(
            name='videogame',
            options={'verbose_name': 'Video Game', 'verbose_name_plural': 'Video Games'},
        ),
        migrations.AlterModelOptions(
            name='videogamecompanymapping',
            options={'verbose_name': 'Video Game - Company Mapping', 'verbose_name_plural': 'Video Games - Company Mappings'},
        ),
        migrations.AlterModelOptions(
            name='videogameconsolemapping',
            options={'verbose_name': 'Video Games - Console Mapping', 'verbose_name_plural': 'Video Games - Console Mappings'},
        ),
        migrations.AlterModelOptions(
            name='videogamefranchise',
            options={'verbose_name': 'Video Game Franchise', 'verbose_name_plural': 'Video Game Franchises'},
        ),
        migrations.AlterModelOptions(
            name='videogamefranchisemapping',
            options={'verbose_name': 'Video Games - Franchise Mapping', 'verbose_name_plural': 'Video Games - Franchise Mappings'},
        ),
        migrations.AlterModelOptions(
            name='videogamefranchisesubcategory',
            options={'verbose_name': 'Video Game Franchise Subcategory', 'verbose_name_plural': 'Video Game Franchise Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='videogamefranchisesubcategorymapping',
            options={'verbose_name': 'Video Games - Franchise  Subcategory Mapping', 'verbose_name_plural': 'Video Games - Franchise  Subcategory Mappings'},
        ),
        migrations.AlterModelOptions(
            name='videogamegenre',
            options={'verbose_name': 'Genre - Video Game', 'verbose_name_plural': 'Genres - Video Games'},
        ),
        migrations.AlterModelOptions(
            name='videogamegenremapping',
            options={'verbose_name': 'Video Games - Genre Mapping', 'verbose_name_plural': 'Video Games - Genre Mappings'},
        ),
        migrations.AlterModelOptions(
            name='videogamepersonmapping',
            options={'verbose_name': 'Video Games - Person Mapping', 'verbose_name_plural': 'Video Games - Person Mappings'},
        ),
        migrations.AlterModelOptions(
            name='webseries',
            options={'verbose_name': 'Web Series', 'verbose_name_plural': 'Web Series'},
        ),
        migrations.AlterModelOptions(
            name='webseriescompanymapping',
            options={'verbose_name': 'Web Series - Company Mapping', 'verbose_name_plural': 'Web Series - Company Mappings'},
        ),
        migrations.AlterModelOptions(
            name='webseriesfranchisemapping',
            options={'verbose_name': 'Web Series - Franchise Mapping', 'verbose_name_plural': 'Web Series - Franchise Mappings'},
        ),
        migrations.AlterModelOptions(
            name='webseriesfranchisesubcategorymapping',
            options={'verbose_name': 'Web Series - Franchise  Subcategory Mapping', 'verbose_name_plural': 'Web Series - Franchise  Subcategory Mappings'},
        ),
        migrations.AlterModelOptions(
            name='webseriesgenremapping',
            options={'verbose_name': 'Web Series - Genre Mapping', 'verbose_name_plural': 'Web Series - Genre Mappings'},
        ),
        migrations.AlterModelOptions(
            name='webseriespersonmapping',
            options={'verbose_name': 'Web Series - Person Mapping', 'verbose_name_plural': 'Web Series - Person Mappings'},
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
    ]
