# Generated by Django 3.0.3 on 2020-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_auto_20200710_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='posterFilePath',
            field=models.CharField(default='../static/media/MissingIcon.png', max_length=500),
        ),
    ]
