# Generated by Django 3.0.3 on 2020-07-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0026_auto_20200710_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
