# Generated by Django 3.0.3 on 2020-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_auto_20200710_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageFilePath',
            field=models.CharField(default='../static/media/MissingIcon.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='imageFilePath',
            field=models.CharField(default='../static/media/MissingIcon.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='television',
            name='posterFilePath',
            field=models.CharField(default='../static/media/MissingIcon.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='posterFilePath',
            field=models.CharField(default='../static/media/MissingIcon.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='posterFilePath',
            field=models.CharField(default='../static/media/MissingIcon.png', max_length=500),
        ),
    ]
