# Generated by Django 3.0.3 on 2020-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0029_auto_20200711_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookfranchisemapping',
            name='orderInFranchise',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='filmfranchisemapping',
            name='orderInFranchise',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='televisionfranchisemapping',
            name='orderInFranchise',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='videogamefranchisemapping',
            name='orderInFranchise',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='webseriesfranchisemapping',
            name='orderInFranchise',
            field=models.IntegerField(default=1),
        ),
    ]
