# Generated by Django 3.0.3 on 2020-07-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0030_auto_20200711_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisesubcategory',
            name='subCategoryOrder',
            field=models.IntegerField(default=1),
        ),
    ]
