# Generated by Django 3.0.3 on 2020-07-12 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0032_franchise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='DoD',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
