# Generated by Django 3.0.3 on 2020-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0033_person_dod'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
