# Generated by Django 3.0.3 on 2020-07-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0036_auto_20200712_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameFranchiseGenreMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchise')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Genre')),
            ],
            options={
                'verbose_name': 'Franchises - Genre Mapping',
                'verbose_name_plural': 'Franchises - Genre Mappings',
            },
        ),
        migrations.CreateModel(
            name='FranchiseGenreMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Genre')),
            ],
            options={
                'verbose_name': 'Franchises - Genre Mapping',
                'verbose_name_plural': 'Franchises - Genre Mappings',
            },
        ),
    ]
