# Generated by Django 3.0.3 on 2020-07-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0037_franchisegenremapping_videogamefranchisegenremapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogamefranchisegenremapping',
            options={'verbose_name': 'Video Game Franchises - Genre Mapping', 'verbose_name_plural': 'Video Game Franchises - Genre Mappings'},
        ),
        migrations.AlterField(
            model_name='videogamefranchisegenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameGenre'),
        ),
    ]
