# Generated by Django 3.0.3 on 2020-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0038_auto_20200714_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailerVideoPath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
