# Generated by Django 3.0.3 on 2020-07-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0039_film_trailervideopath'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSeriesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(default='', max_length=500)),
                ('webSeries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.WebSeries')),
            ],
            options={
                'verbose_name': 'Web Series - Additional Image',
                'verbose_name_plural': 'Web Series - Additional Images',
            },
        ),
        migrations.CreateModel(
            name='VideoGameImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(default='', max_length=500)),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
            ],
            options={
                'verbose_name': 'Video Game - Additional Image',
                'verbose_name_plural': 'Video Games - Additional Images',
            },
        ),
        migrations.CreateModel(
            name='TelevisionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(default='', max_length=500)),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Television')),
            ],
            options={
                'verbose_name': 'Television - Additional Image',
                'verbose_name_plural': 'Television - Additional Images',
            },
        ),
        migrations.CreateModel(
            name='FilmImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(default='', max_length=500)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Film')),
            ],
            options={
                'verbose_name': 'Film - Additional Image',
                'verbose_name_plural': 'Films - Additional Images',
            },
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(default='', max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Book')),
            ],
            options={
                'verbose_name': 'Book - Additional Image',
                'verbose_name_plural': 'Books - Additional Images',
            },
        ),
    ]
