# Generated by Django 3.0.3 on 2020-07-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0040_bookimages_filmimages_televisionimages_videogameimages_webseriesimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(default='', max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Person')),
            ],
            options={
                'verbose_name': 'Person - Additional Image',
                'verbose_name_plural': 'People - Additional Images',
            },
        ),
    ]
