# Generated by Django 3.0.3 on 2020-07-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0041_personimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='DoD',
            field=models.DateField(blank=True, null=True),
        ),
    ]
