# Generated by Django 3.0.3 on 2020-07-15 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0042_auto_20200715_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='trailerVideoPath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='television',
            name='end',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
