# Generated by Django 3.0.3 on 2020-07-20 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0044_awardtype_bookawardmapping_filmawardmapping_televisionawardmapping_videogameawardmapping_webseriesaw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardtype',
            options={'verbose_name': 'Awards - Type', 'verbose_name_plural': 'Awards - Types'},
        ),
        migrations.RemoveField(
            model_name='bookawardmapping',
            name='award',
        ),
        migrations.RemoveField(
            model_name='filmawardmapping',
            name='award',
        ),
        migrations.RemoveField(
            model_name='televisionawardmapping',
            name='award',
        ),
        migrations.RemoveField(
            model_name='videogameawardmapping',
            name='award',
        ),
        migrations.RemoveField(
            model_name='webseriesawardmapping',
            name='award',
        ),
        migrations.CreateModel(
            name='AwardsShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.AwardType')),
            ],
            options={
                'verbose_name': 'Awards - Show',
                'verbose_name_plural': 'Awards - Shows',
            },
        ),
        migrations.AddField(
            model_name='bookawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
        migrations.AddField(
            model_name='filmawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
        migrations.AddField(
            model_name='televisionawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
        migrations.AddField(
            model_name='videogameawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
        migrations.AddField(
            model_name='webseriesawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
    ]
