# Generated by Django 3.0.3 on 2020-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0045_auto_20200720_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookawardmapping',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filmawardmapping',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='televisionawardmapping',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videogameawardmapping',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webseriesawardmapping',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
