# Generated by Django 3.0.3 on 2020-07-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0046_auto_20200720_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='personimages',
            name='awardsShow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
    ]
