# Generated by Django 3.0.3 on 2020-07-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0047_personimages_awardsshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('awardType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.AwardType')),
            ],
            options={
                'verbose_name': 'Awards - Category',
                'verbose_name_plural': 'Awards - Categories',
            },
        ),
        migrations.AlterField(
            model_name='bookawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='filmawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='televisionawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='videogameawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='webseriesawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
    ]
