# Generated by Django 3.0.3 on 2020-07-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0048_auto_20200720_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmAwardMapping',
        ),
    ]
