# Generated by Django 3.0.3 on 2020-07-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0049_delete_filmawardmapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardscategories',
            options={},
        ),
        migrations.AlterField(
            model_name='bookawardmapping',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='televisionawardmapping',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videogameawardmapping',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='webseriesawardmapping',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FilmAwardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('win', models.BooleanField(default=False)),
                ('awardsShow', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Film')),
            ],
            options={
                'verbose_name': 'Film - Award',
                'verbose_name_plural': 'Films - Awards',
            },
        ),
    ]
