# Generated by Django 3.0.3 on 2020-07-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0050_auto_20200720_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardscategories',
            options={'verbose_name': 'Awards - Category', 'verbose_name_plural': 'Awards - Categories'},
        ),
        migrations.AlterField(
            model_name='bookawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='filmawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='televisionawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='videogameawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='webseriesawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
    ]
