# Generated by Django 3.0.3 on 2020-07-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0051_auto_20200720_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookawardmapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filmawardmapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='televisionawardmapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videogameawardmapping',
            name='category',
        ),
        migrations.RemoveField(
            model_name='webseriesawardmapping',
            name='category',
        ),
    ]
