# Generated by Django 3.0.3 on 2020-07-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0052_auto_20200720_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AddField(
            model_name='filmawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AddField(
            model_name='televisionawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AddField(
            model_name='videogameawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
        migrations.AddField(
            model_name='webseriesawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsCategories'),
        ),
    ]
