# Generated by Django 3.0.3 on 2020-07-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0053_auto_20200720_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardscategories',
            name='personType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='media.PersonRole'),
        ),
    ]
