# Generated by Django 3.0.3 on 2020-07-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0056_remove_awardscategories_persontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmawardpersonmapping',
            options={'verbose_name': 'Film - Award Peron Mapping', 'verbose_name_plural': 'Films - Award Person Mappings'},
        ),
        migrations.CreateModel(
            name='FilmAwardCompanyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('FilmAwardMapping', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.FilmAwardMapping')),
            ],
            options={
                'verbose_name': 'Film - Award Company Mapping',
                'verbose_name_plural': 'Films - Award Company Mappings',
            },
        ),
    ]
