# Generated by Django 3.0.3 on 2020-07-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0058_awardscategories_categoryorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAwardCreditMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookAwardMapping', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.BookAwardMapping')),
                ('Company', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('Person', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Person')),
            ],
            options={
                'verbose_name': 'Book - Award Credit Mapping',
                'verbose_name_plural': 'Books - Award Credit Mappings',
            },
        ),
        migrations.CreateModel(
            name='FilmAwardCreditMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('FilmAwardMapping', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.FilmAwardMapping')),
                ('Person', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Person')),
            ],
            options={
                'verbose_name': 'Film - Award Credit Mapping',
                'verbose_name_plural': 'Films - Award Credit Mappings',
            },
        ),
        migrations.CreateModel(
            name='TelevisionAwardCreditMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('Person', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Person')),
                ('TelevisionAwardMapping', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.TelevisionAwardMapping')),
            ],
            options={
                'verbose_name': 'Television - Award Credit Mapping',
                'verbose_name_plural': 'Television - Award Credit Mappings',
            },
        ),
        migrations.CreateModel(
            name='VideoGameAwardCreditMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('Person', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Person')),
                ('VideoGameAwardMapping', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameAwardMapping')),
            ],
            options={
                'verbose_name': 'Video Game - Award Credit Mapping',
                'verbose_name_plural': 'Video Games - Award Credit Mappings',
            },
        ),
        migrations.CreateModel(
            name='WebSeriesAwardCreditMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('Person', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='media.Person')),
                ('WebSeriesAwardMapping', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.WebSeriesAwardMapping')),
            ],
            options={
                'verbose_name': 'Web Series - Award Credit Mapping',
                'verbose_name_plural': 'Web Series - Award Credit Mappings',
            },
        ),
        migrations.RemoveField(
            model_name='filmawardpersonmapping',
            name='FilmAwardMapping',
        ),
        migrations.RemoveField(
            model_name='filmawardpersonmapping',
            name='Person',
        ),
        migrations.DeleteModel(
            name='FilmAwardCompanyMapping',
        ),
        migrations.DeleteModel(
            name='FilmAwardPersonMapping',
        ),
    ]
