# Generated by Django 3.0.3 on 2020-07-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0059_auto_20200721_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='bookawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='filmawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='filmawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='televisionawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='televisionawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='videogameawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='videogameawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='webseriesawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='webseriesawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Person'),
        ),
    ]
