# Generated by Django 3.0.3 on 2020-07-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0061_miscimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimages',
            name='awardsShow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.AwardsShow'),
        ),
    ]
