# Generated by Django 3.0.3 on 2020-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0062_auto_20200721_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookawardcreditmapping',
            name='personCompanyPriority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filmawardcreditmapping',
            name='personCompanyPriority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='televisionawardcreditmapping',
            name='personCompanyPriority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videogameawardcreditmapping',
            name='personCompanyPriority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webseriesawardcreditmapping',
            name='personCompanyPriority',
            field=models.BooleanField(default=True),
        ),
    ]
