# Generated by Django 3.0.3 on 2020-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0063_auto_20200722_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookawardcreditmapping',
            name='personCompanyPriority',
        ),
        migrations.RemoveField(
            model_name='filmawardcreditmapping',
            name='personCompanyPriority',
        ),
        migrations.RemoveField(
            model_name='televisionawardcreditmapping',
            name='personCompanyPriority',
        ),
        migrations.RemoveField(
            model_name='videogameawardcreditmapping',
            name='personCompanyPriority',
        ),
        migrations.RemoveField(
            model_name='webseriesawardcreditmapping',
            name='personCompanyPriority',
        ),
        migrations.AddField(
            model_name='awardscategories',
            name='personCompanyPriority',
            field=models.BooleanField(default=False),
        ),
    ]
