# Generated by Django 3.0.3 on 2020-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0064_auto_20200722_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogamefranchisesubcategory',
            name='subCategoryOrder',
            field=models.IntegerField(default=1),
        ),
    ]
