# Generated by Django 3.0.3 on 2020-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0067_film_coverimagefilepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='coverImageFilePath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='television',
            name='coverImageFilePath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='videogame',
            name='coverImageFilePath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='videogame',
            name='trailerVideoPath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webseries',
            name='coverImageFilePath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='webseries',
            name='trailerVideoPath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
