# Generated by Django 3.0.3 on 2020-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0068_auto_20200820_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='people'),
        ),
    ]
