# Generated by Django 3.0.3 on 2020-08-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0070_auto_20200825_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='misc'),
        ),
    ]
