# Generated by Django 3.0.3 on 2020-08-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0071_miscimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personimages',
            name='filePath',
        ),
    ]
