# Generated by Django 3.0.3 on 2020-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0072_remove_personimages_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimages',
            name='filePath',
        ),
        migrations.AddField(
            model_name='bookimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='extraImages'),
        ),
        migrations.AddField(
            model_name='filmimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='extraImages'),
        ),
        migrations.AddField(
            model_name='televisionimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='extraImages'),
        ),
        migrations.AddField(
            model_name='videogameimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='extraImages'),
        ),
        migrations.AddField(
            model_name='webseriesimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='extraImages'),
        ),
    ]
