# Generated by Django 3.0.3 on 2020-08-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0073_auto_20200825_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='coverImages'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='posters'),
        ),
        migrations.AddField(
            model_name='film',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='coverImages'),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters'),
        ),
        migrations.AddField(
            model_name='television',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='coverImages'),
        ),
        migrations.AddField(
            model_name='television',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='coverImages'),
        ),
        migrations.AddField(
            model_name='videogame',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters'),
        ),
        migrations.AddField(
            model_name='webseries',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='coverImages'),
        ),
        migrations.AddField(
            model_name='webseries',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='miscimages',
            name='image',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='miscImages'),
        ),
    ]
