# Generated by Django 3.0.3 on 2020-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0075_auto_20200827_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='image',
            field=models.ImageField(blank=True, upload_to='franchises'),
        ),
    ]
