# Generated by Django 3.0.3 on 2020-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0076_franchise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogamefranchise',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videogamefranchise',
            name='image',
            field=models.ImageField(blank=True, upload_to='franchises'),
        ),
    ]
