# Generated by Django 3.0.3 on 2020-09-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0077_auto_20200827_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='coverImages'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='MissingIcon.png', upload_to='posters'),
        ),
    ]
