# Generated by Django 3.0.3 on 2020-09-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0079_auto_20200901_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='boxOffice',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='film',
            name='posterFilePath',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
