# Generated by Django 3.0.3 on 2020-09-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0080_auto_20200901_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='boxOffice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='budget',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.IntegerField(blank=True),
        ),
    ]
