# Generated by Django 3.0.3 on 2020-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0082_auto_20200901_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
