# Generated by Django 3.0.3 on 2020-09-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0083_film_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
