# Generated by Django 3.0.3 on 2020-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0084_television_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
