# Generated by Django 3.0.3 on 2020-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0085_videogame_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='webseries',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
