# Generated by Django 3.0.3 on 2020-09-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0086_auto_20200908_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='FilmTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Film')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Tag')),
            ],
            options={
                'verbose_name': 'Film - Tag',
                'verbose_name_plural': 'Films - Tags',
            },
        ),
    ]
