# Generated by Django 3.0.3 on 2020-10-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0087_filmtagmapping_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='television',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='webseries',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
