# Generated by Django 3.0.3 on 2020-10-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0089_auto_20201014_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGenreMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Genre')),
            ],
            options={
                'verbose_name': 'Company - Genre Mapping',
                'verbose_name_plural': 'Companies - Genre Mappings',
            },
        ),
    ]
