# Generated by Django 3.0.3 on 2020-10-14 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0090_companygenremapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseCompanyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('franchise', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.Franchise')),
            ],
            options={
                'verbose_name': 'Company - Franchise Mapping',
                'verbose_name_plural': 'Companies - Franchise Mappings',
            },
        ),
        migrations.CreateModel(
            name='VideoGameFranchiseCompanyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.Company')),
                ('franchise', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchise')),
            ],
            options={
                'verbose_name': 'Company - Video Game Franchise Mapping',
                'verbose_name_plural': 'Companies - Video Game Franchise Mappings',
            },
        ),
        migrations.DeleteModel(
            name='CompanyGenreMapping',
        ),
    ]
