# Generated by Django 3.0.3 on 2020-10-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0091_auto_20201014_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
