# Generated by Django 3.0.3 on 2020-10-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0092_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
