# Generated by Django 3.0.3 on 2020-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0094_videogamefranchise_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150),
        ),
    ]
