# Generated by Django 3.0.3 on 2020-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0095_console_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='image',
            field=models.ImageField(blank=True, upload_to='consoles'),
        ),
        migrations.AlterField(
            model_name='console',
            name='imageFilePath',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
