# Generated by Django 3.0.3 on 2020-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0096_auto_20201015_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, upload_to='companyLogos'),
        ),
    ]
