# Generated by Django 3.0.3 on 2020-10-21 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0097_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoConsoleNameSpecified', max_length=500)),
                ('release', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='consoles')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Console')),
            ],
            options={
                'verbose_name': 'Video Game Console - Version',
                'verbose_name_plural': 'Video Game Consoles - Versions',
            },
        ),
    ]
