# Generated by Django 3.0.3 on 2020-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0098_consoleversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consoleversion',
            name='shortName',
            field=models.CharField(default=models.CharField(default='NoConsoleNameSpecified', max_length=500), max_length=500),
        ),
    ]
