# Generated by Django 3.0.3 on 2020-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0099_consoleversion_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmfranchisemapping',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmfranchisemapping',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='televisionfranchisemapping',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='televisionfranchisemapping',
            name='television',
        ),
        migrations.RemoveField(
            model_name='videogamefranchisemapping',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='videogamefranchisemapping',
            name='videoGame',
        ),
        migrations.RemoveField(
            model_name='webseriesfranchisemapping',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='webseriesfranchisemapping',
            name='webSeries',
        ),
        migrations.AlterField(
            model_name='consoleversion',
            name='shortName',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.DeleteModel(
            name='BookFranchiseMapping',
        ),
        migrations.DeleteModel(
            name='FilmFranchiseMapping',
        ),
        migrations.DeleteModel(
            name='TelevisionFranchiseMapping',
        ),
        migrations.DeleteModel(
            name='VideoGameFranchiseMapping',
        ),
        migrations.DeleteModel(
            name='WebSeriesFranchiseMapping',
        ),
    ]
