# Generated by Django 3.0.3 on 2020-11-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0100_auto_20201022_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmtagmapping',
            options={'verbose_name': 'Film - Tag Mapping', 'verbose_name_plural': 'Films - Tag Mappings'},
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, default='NoSurnameSpecified', max_length=500),
        ),
        migrations.CreateModel(
            name='TelevisionTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Tag')),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Television')),
            ],
            options={
                'verbose_name': 'Film - Tag Mapping',
                'verbose_name_plural': 'Television - Tag Mappings',
            },
        ),
    ]
