# Generated by Django 3.0.3 on 2020-11-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0101_auto_20201117_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisiontagmapping',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='televisiontagmapping',
            name='television',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='FilmTagMapping',
        ),
        migrations.DeleteModel(
            name='TelevisionTagMapping',
        ),
    ]
