# Generated by Django 3.0.3 on 2020-11-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0103_filmtagmapping_televisiontagmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisiontagmapping',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='televisiontagmapping',
            name='television',
        ),
        migrations.DeleteModel(
            name='FilmTagMapping',
        ),
        migrations.DeleteModel(
            name='TelevisionTagMapping',
        ),
    ]
