# Generated by Django 3.0.3 on 2020-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0104_auto_20201117_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(default='', primary_key=True, serialize=False),
        ),
    ]
