# Generated by Django 3.0.3 on 2020-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0105_auto_20201117_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
