# Generated by Django 3.0.3 on 2020-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0107_filmtagmapping_televisiontagmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
