# Generated by Django 3.0.3 on 2021-01-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0108_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='coverImageFilePath',
        ),
        migrations.RemoveField(
            model_name='film',
            name='posterFilePath',
        ),
    ]
