# Generated by Django 3.0.3 on 2021-01-28 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0109_auto_20210115_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='imageFilePath',
        ),
        migrations.AlterField(
            model_name='person',
            name='DoB',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
