# Generated by Django 3.0.3 on 2021-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0110_auto_20210128_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='DoB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
