# Generated by Django 3.0.3 on 2021-02-02 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0111_auto_20210128_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='end',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
