# Generated by Django 3.0.3 on 2021-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0113_franchise_showpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='showProducers',
            field=models.BooleanField(default=False),
        ),
    ]
