# Generated by Django 3.0.3 on 2021-03-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0114_franchise_showproducers'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='icons'),
        ),
    ]
