# Generated by Django 3.0.3 on 2021-03-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0115_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogamegenre',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='icons'),
        ),
    ]
