# Generated by Django 3.0.3 on 2021-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0116_videogamegenre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(default='NoGenreSpecified', max_length=500),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='synopsis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
