# Generated by Django 3.0.3 on 2021-03-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0117_auto_20210315_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='baseCountry',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='dateFounded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
