# Generated by Django 3.0.3 on 2021-03-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0118_auto_20210315_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameVideoGameFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
                ('videoGameFranchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGameFranchiseSubcategory')),
            ],
            options={
                'verbose_name': 'Video Games - Video Game Franchise  Subcategory Mapping',
                'verbose_name_plural': 'Video Games - Video Game Franchise  Subcategory Mappings',
            },
        ),
        migrations.DeleteModel(
            name='VideoGameFranchiseSubcategoryMapping',
        ),
    ]
