# Generated by Django 3.0.3 on 2021-03-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0119_auto_20210319_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.FranchiseSubcategory')),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
            ],
            options={
                'verbose_name': 'Video Games - Franchise  Subcategory Mapping',
                'verbose_name_plural': 'Video Games - Franchise  Subcategory Mappings',
            },
        ),
    ]
