# Generated by Django 3.0.3 on 2021-03-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0120_videogamefranchisesubcategorymapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='coverImageFilePath',
        ),
        migrations.RemoveField(
            model_name='book',
            name='imageFilePath',
        ),
        migrations.RemoveField(
            model_name='console',
            name='imageFilePath',
        ),
        migrations.RemoveField(
            model_name='franchise',
            name='posterFilePath',
        ),
        migrations.RemoveField(
            model_name='television',
            name='coverImageFilePath',
        ),
        migrations.RemoveField(
            model_name='television',
            name='posterFilePath',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='coverImageFilePath',
        ),
        migrations.RemoveField(
            model_name='videogame',
            name='posterFilePath',
        ),
        migrations.RemoveField(
            model_name='videogamefranchise',
            name='posterFilePath',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='coverImageFilePath',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='posterFilePath',
        ),
    ]
