# Generated by Django 3.0.3 on 2021-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0122_auto_20210319_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogamepersonmapping',
            name='billing',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='videogamepersonmapping',
            name='character',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
