# Generated by Django 3.0.3 on 2021-03-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0123_auto_20210319_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameConsoleFeaturedMappings',
            fields=[
                ('videogameconsolemapping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.VideoGameConsoleMapping')),
            ],
            options={
                'verbose_name': 'Video Games - Console (Featured) Mapping',
                'verbose_name_plural': 'Video Games - Console (Featured) Mappings',
            },
            bases=('media.videogameconsolemapping',),
        ),
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ImageField(blank=True, upload_to='coverImages'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(default='NoFilmTitleSpecified', max_length=150),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailerVideoPath',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
