# Generated by Django 3.0.3 on 2021-03-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0124_auto_20210324_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoGameConsoleFeaturedMappings',
            new_name='VideoGameConsoleFeaturedMapping',
        ),
    ]
