# Generated by Django 3.0.3 on 2021-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0125_auto_20210324_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoGameConsoleFeaturedMapping',
        ),
    ]
