# Generated by Django 3.0.3 on 2021-03-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0126_delete_videogameconsolefeaturedmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGameConsoleMappingFeatured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.Console')),
                ('featuredVideoGame', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
            ],
            options={
                'verbose_name': 'Video Games - Console (Featured) Mapping',
                'verbose_name_plural': 'Video Games - Console (Featured) Mappings',
            },
        ),
    ]
