# Generated by Django 3.0.3 on 2021-03-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0127_videogameconsolemappingfeatured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoGameConsoleMappingFeatured',
        ),
    ]
