# Generated by Django 3.0.3 on 2021-03-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0128_delete_videogameconsolemappingfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogameconsolemapping',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
