# Generated by Django 3.0.3 on 2021-03-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0129_videogameconsolemapping_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamecompanymapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='videogamecompanymapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.CompanyRole'),
        ),
        migrations.AlterField(
            model_name='videogamecompanymapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogameconsolemapping',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Console'),
        ),
        migrations.AlterField(
            model_name='videogameconsolemapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogamegenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameGenre'),
        ),
        migrations.AlterField(
            model_name='videogamegenremapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.CreateModel(
            name='HighestRatedFilms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film')),
            ],
            options={
                'verbose_name': 'Highest Rated Film',
                'verbose_name_plural': 'Highest Rated Films',
            },
        ),
    ]
