# Generated by Django 3.0.3 on 2021-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0130_auto_20210325_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='highestratedfilms',
            name='rating',
            field=models.FloatField(default=1.0),
        ),
    ]
