# Generated by Django 3.0.3 on 2021-03-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0131_highestratedfilms_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highestratedfilms',
            old_name='film',
            new_name='media',
        ),
        migrations.CreateModel(
            name='HighestRatedWebSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0)),
                ('rank', models.IntegerField(default=1)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries')),
            ],
            options={
                'verbose_name': 'Highest Rated Web Series',
                'verbose_name_plural': 'Highest Rated Web Series',
            },
        ),
        migrations.CreateModel(
            name='HighestRatedVideoGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0)),
                ('rank', models.IntegerField(default=1)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame')),
            ],
            options={
                'verbose_name': 'Highest Rated Video Game',
                'verbose_name_plural': 'Highest Rated Video Games',
            },
        ),
        migrations.CreateModel(
            name='HighestRatedTelevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0)),
                ('rank', models.IntegerField(default=1)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television')),
            ],
            options={
                'verbose_name': 'Highest Rated Television',
                'verbose_name_plural': 'Highest Rated Television',
            },
        ),
        migrations.CreateModel(
            name='HighestRatedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1.0)),
                ('rank', models.IntegerField(default=1)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book')),
            ],
            options={
                'verbose_name': 'Highest Rated Book',
                'verbose_name_plural': 'Highest Rated Book',
            },
        ),
    ]
