# Generated by Django 3.0.3 on 2021-03-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0133_auto_20210327_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogameawardcreditmapping',
            name='VideoGameAwardMapping',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameAwardMapping'),
        ),
        migrations.AlterField(
            model_name='videogameawardmapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisesubcategory',
            name='parentFranchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameFranchise'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisesubcategorymapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogameimages',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogamepersonmapping',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='videogamepersonmapping',
            name='videogame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='videogamevideogamefranchisesubcategorymapping',
            name='videoGameFranchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameFranchiseSubcategory'),
        ),
        migrations.CreateModel(
            name='VideoGameTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Tag')),
                ('videoGame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.VideoGame')),
            ],
            options={
                'verbose_name': 'Video Game - Tag Mapping',
                'verbose_name_plural': 'Video Game - Tag Mappings',
            },
        ),
    ]
