# Generated by Django 3.0.3 on 2021-03-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0134_auto_20210329_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSeriesTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Tag')),
                ('webSeries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.WebSeries')),
            ],
            options={
                'verbose_name': 'Web Series - Tag Mapping',
                'verbose_name_plural': 'Web Series - Tag Mappings',
            },
        ),
        migrations.CreateModel(
            name='BookTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Tag')),
            ],
            options={
                'verbose_name': 'Book - Tag Mapping',
                'verbose_name_plural': 'Book - Tag Mappings',
            },
        ),
    ]
