# Generated by Django 3.0.3 on 2021-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0135_booktagmapping_webseriestagmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='videogamegenre',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150),
        ),
    ]
