# Generated by Django 3.0.3 on 2021-04-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0136_auto_20210330_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='releaseYear',
            field=models.CharField(default='2000', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
