# Generated by Django 3.0.3 on 2021-04-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0139_bookgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.BookGenre'),
        ),
    ]
