# Generated by Django 3.0.3 on 2021-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0140_auto_20210414_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
