# Generated by Django 3.0.3 on 2025-01-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0141_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdbid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='awardscategories',
            name='awardType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.AwardType'),
        ),
        migrations.AlterField(
            model_name='awardsshow',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.AwardType'),
        ),
        migrations.AlterField(
            model_name='bookawardcreditmapping',
            name='BookAwardMapping',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.BookAwardMapping'),
        ),
        migrations.AlterField(
            model_name='bookawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='bookawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='bookawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='bookawardmapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='bookcompanymapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookcompanymapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='bookcompanymapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.CompanyRole'),
        ),
        migrations.AlterField(
            model_name='bookfranchisesubcategorymapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='bookgenremapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookgenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.BookGenre'),
        ),
        migrations.AlterField(
            model_name='bookimages',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookpersonmapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='bookpersonmapping',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='bookpersonmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.PersonRole'),
        ),
        migrations.AlterField(
            model_name='booktagmapping',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Book'),
        ),
        migrations.AlterField(
            model_name='booktagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Tag'),
        ),
        migrations.AlterField(
            model_name='console',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='consoleversion',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Console'),
        ),
        migrations.AlterField(
            model_name='filmawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='filmawardcreditmapping',
            name='FilmAwardMapping',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.FilmAwardMapping'),
        ),
        migrations.AlterField(
            model_name='filmawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='filmawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='filmawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='filmawardmapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmcompanymapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='filmcompanymapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmcompanymapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.CompanyRole'),
        ),
        migrations.AlterField(
            model_name='filmfranchisesubcategorymapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='filmgenremapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmgenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Genre'),
        ),
        migrations.AlterField(
            model_name='filmimages',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmpersonmapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmpersonmapping',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='filmpersonmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.PersonRole'),
        ),
        migrations.AlterField(
            model_name='filmtagmapping',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Film'),
        ),
        migrations.AlterField(
            model_name='filmtagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Tag'),
        ),
        migrations.AlterField(
            model_name='franchisecompanymapping',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='franchisecompanymapping',
            name='franchise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.Franchise'),
        ),
        migrations.AlterField(
            model_name='franchisegenremapping',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Franchise'),
        ),
        migrations.AlterField(
            model_name='franchisegenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Genre'),
        ),
        migrations.AlterField(
            model_name='franchisesubcategory',
            name='parentFranchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Franchise'),
        ),
        migrations.AlterField(
            model_name='miscimages',
            name='awardsShow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='personimages',
            name='awardsShow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='personimages',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='televisionawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='televisionawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='televisionawardcreditmapping',
            name='TelevisionAwardMapping',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.TelevisionAwardMapping'),
        ),
        migrations.AlterField(
            model_name='televisionawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='televisionawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='televisionawardmapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisioncompanymapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='televisioncompanymapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.CompanyRole'),
        ),
        migrations.AlterField(
            model_name='televisioncompanymapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisionfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='televisionfranchisesubcategorymapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisiongenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Genre'),
        ),
        migrations.AlterField(
            model_name='televisiongenremapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisionimages',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisionpersonmapping',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='televisionpersonmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.PersonRole'),
        ),
        migrations.AlterField(
            model_name='televisionpersonmapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='televisiontagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Tag'),
        ),
        migrations.AlterField(
            model_name='televisiontagmapping',
            name='television',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Television'),
        ),
        migrations.AlterField(
            model_name='videogameawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='videogameawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='videogameawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='videogameawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisecompanymapping',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisecompanymapping',
            name='franchise',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameFranchise'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisegenremapping',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameFranchise'),
        ),
        migrations.AlterField(
            model_name='videogamefranchisegenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGameGenre'),
        ),
        migrations.AlterField(
            model_name='videogamepersonmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.PersonRole'),
        ),
        migrations.AlterField(
            model_name='videogametagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Tag'),
        ),
        migrations.AlterField(
            model_name='videogametagmapping',
            name='videoGame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.VideoGame'),
        ),
        migrations.AlterField(
            model_name='webseriesawardcreditmapping',
            name='Company',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='webseriesawardcreditmapping',
            name='Person',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='webseriesawardcreditmapping',
            name='WebSeriesAwardMapping',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.WebSeriesAwardMapping'),
        ),
        migrations.AlterField(
            model_name='webseriesawardmapping',
            name='awardsShow',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='media.AwardsShow'),
        ),
        migrations.AlterField(
            model_name='webseriesawardmapping',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.AwardsCategories'),
        ),
        migrations.AlterField(
            model_name='webseriesawardmapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='webseriescompanymapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Company'),
        ),
        migrations.AlterField(
            model_name='webseriescompanymapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.CompanyRole'),
        ),
        migrations.AlterField(
            model_name='webseriescompanymapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='webseriesfranchisesubcategorymapping',
            name='franchiseSubcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.FranchiseSubcategory'),
        ),
        migrations.AlterField(
            model_name='webseriesfranchisesubcategorymapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='webseriesgenremapping',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Genre'),
        ),
        migrations.AlterField(
            model_name='webseriesgenremapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='webseriesimages',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='webseriespersonmapping',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Person'),
        ),
        migrations.AlterField(
            model_name='webseriespersonmapping',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.PersonRole'),
        ),
        migrations.AlterField(
            model_name='webseriespersonmapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
        migrations.AlterField(
            model_name='webseriestagmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Tag'),
        ),
        migrations.AlterField(
            model_name='webseriestagmapping',
            name='webSeries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.WebSeries'),
        ),
    ]
