# Generated by Django 3.0.3 on 2025-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0142_auto_20250117_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tmdbid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
