# Generated by Django 3.0.3 on 2025-01-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0143_person_tmdbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
    ]
