# Generated by Django 3.0.3 on 2025-01-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0146_auto_20250122_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tmdbid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
