# Generated by Django 3.0.3 on 2025-01-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0147_company_tmdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpersonmapping',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='media.Department'),
        ),
        migrations.AddField(
            model_name='televisionpersonmapping',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='media.Department'),
        ),
        migrations.AddField(
            model_name='videogamepersonmapping',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='media.Department'),
        ),
        migrations.AddField(
            model_name='webseriespersonmapping',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='media.Department'),
        ),
    ]
