# Generated by Django 3.0.3 on 2025-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0148_auto_20250122_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='posterSmall',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
