# Generated by Django 3.0.3 on 2025-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0149_film_postersmall'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imageSmall',
            field=models.ImageField(blank=True, default='MissingIcon.png', null=True, upload_to='people'),
        ),
        migrations.AlterField(
            model_name='film',
            name='cover',
            field=models.ImageField(blank=True, upload_to='filmCoverImages'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='filmPosters'),
        ),
        migrations.AlterField(
            model_name='film',
            name='posterSmall',
            field=models.ImageField(blank=True, null=True, upload_to='filmPosters'),
        ),
    ]
