# Generated by Django 3.0.3 on 2025-01-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0151_auto_20250127_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='televisionseason',
            old_name='episodeNumber',
            new_name='episodeCount',
        ),
    ]
