# Generated by Django 3.0.3 on 2025-01-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0152_auto_20250127_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='television',
            old_name='episodes',
            new_name='episodeCount',
        ),
        migrations.RenameField(
            model_name='television',
            old_name='seasons',
            new_name='seasonCount',
        ),
        migrations.RenameField(
            model_name='televisionseason',
            old_name='seasonNmber',
            new_name='seasonNumber',
        ),
    ]
