# Generated by Django 3.0.3 on 2025-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0155_auto_20250127_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='television',
            name='poster',
        ),
        migrations.AddField(
            model_name='televisionseason',
            name='posterSmall',
            field=models.ImageField(blank=True, default='', null=True, upload_to='televisionPosters'),
        ),
        migrations.AlterField(
            model_name='television',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='televisionCoverImages'),
        ),
    ]
