# Generated by Django 3.0.3 on 2025-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0156_auto_20250127_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='poster',
            field=models.ImageField(blank=True, default='', null=True, upload_to='televisionPosters'),
        ),
        migrations.AddField(
            model_name='television',
            name='posterSmall',
            field=models.ImageField(blank=True, default='', null=True, upload_to='televisionPosters'),
        ),
    ]
