# Generated by Django 3.0.3 on 2025-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0157_auto_20250127_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisionepisode',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='televisionepisode',
            name='poster',
        ),
        migrations.AddField(
            model_name='televisionepisode',
            name='stillImage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='televisionStills'),
        ),
    ]
