# Generated by Django 3.0.3 on 2025-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0159_auto_20250127_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisionepisodepersonmapping',
            name='seriesCast',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
