# Generated by Django 3.0.3 on 2025-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0160_televisionepisodepersonmapping_seriescast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='televisionepisodepersonmapping',
            name='seriesCast',
        ),
        migrations.AddField(
            model_name='televisionepisodepersonmapping',
            name='guestCast',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
