# Generated by Django 3.0.3 on 2025-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0161_auto_20250128_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='episodeCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='television',
            name='seasonCount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
