# Generated by Django 3.0.3 on 2025-01-30 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0162_auto_20250130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='release',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
