# Generated by Django 3.0.3 on 2025-02-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0163_television_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelevisionSeasonFranchiseSubcategoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderInFranchise', models.IntegerField(default=1)),
                ('franchiseSubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.FranchiseSubcategory')),
                ('televisionSeason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.TelevisionSeason')),
            ],
            options={
                'verbose_name': 'Television Season - Franchise  Subcategory Mapping',
                'verbose_name_plural': 'Television Season - Franchise  Subcategory Mappings',
            },
        ),
    ]
