# Generated by Django 3.0.3 on 2025-02-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0164_televisionseasonfranchisesubcategorymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='trailerVideoPath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
